version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/fe/build/
    overwrite: yes
permissions:
  - object: /home/ubuntu/fe/build/
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: build.sh
      timeout: 1000
      runas: root
